# Generated by Django 4.2.13 on 2026-07-08 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active_lockers', models.PositiveIntegerField(default=0)),
                ('synced', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('offline_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GestureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('symbols', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('key', models.JSONField(blank=True, default=list)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='lockers.controller')),
            ],
            options={
                'ordering': ['controller', 'number'],
                'unique_together': {('controller', 'number')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesture_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lockers.gesturemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Apertura'), ('close', 'Cierre'), ('denied', 'Rechazado')], max_length=10)),
                ('ts', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lockers.locker')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
